### ISSUE TITLE
Does'nt Work

### ISSUE THREAD

**Issue by garvit-joshi** [akueisara/hackerrank#1]
The program Has Not Worked In HackerRank IDLE . I Made A code It Is simpler But Cannot pass Last Test-case Because Of Runtime Error
`import statistics as st
n=int(input())
lis=list(map(int,input().split()))
print(st.mean(lis))
print(st.median(lis))
s=set(lis)
if len(s)==len(lis):
    print(min(lis))
else:
    print(st.mode(lis))`

**Comment by akueisara** [comment]
Sorry, I'm not sure which question you are referring to?

**Comment by garvit-joshi** [comment]
Your Repository :hackerrank/10-days-of-statistics/day-0-mean-median-and-mode/Solution.py
Sorry For The Inconvenience , I Am New To Github ,Was Unable To Put the issue.
I Pasted Your code ,But It did'nt Worked On The Hackerrank IDLE

**Comment by akueisara** [comment]
Hi, the code only works in Python 2.
If you want to run it in Python 3, you need to change some part of the code.
I will update the code. 
If you would like to contribute, you can pull a request after you change the code.
Thanks!

**Comment by garvit-joshi** [comment]
Thanku Mam !!
